### ISSUE TITLE
Can not show Curly brackets

### ISSUE THREAD

**Issue by ZhiliangWu** [orsharir/github-mathjax#10]
I write it in markdown like $\Omega=\{\omega_1, ..., \omega_N\}$
However, it does not show the curly bracket. Is there any trick?
Thanks in advance.

**Comment by orsharir** [comment]
This is for LaTeX format, for which curly bracket are part of the syntax, so you'll have to escape them with slash.

**Comment by ZhiliangWu** [comment]
Thanks for your reply. Actually, I escaped it. The code between $$ are `\Omega=\{\omega_1, ..., \omega_N\}`. However, the slash before the curly bracket disappeared for some certain reason. The only way to make it to show now is to give double slash. Is it possible to improve it?

**Comment by orsharir** [comment]
Okay, now I understand what you mean. This is due to Github's use of backslash. You have to escape the backslash first to make it work (otherwise the single slash would show in the comment in the first place). Alternatively, you can use \lbrace and \rbrace, like so $\lbrace 1,2,3 \rbrace$.

**Comment by ZhiliangWu** [comment]
Great! That's really what I want! Thanks for the solution.

**Comment by jxu** [comment]
If you are coming here because of github's native markdown renderer, see https://github.com/orgs/community/discussions/16993
