### ISSUE TITLE
Appears to only work on the root page of a repo

### ISSUE THREAD

**Issue by adefazio** [orsharir/github-mathjax#3]
For example, the equation on this very repo renders when viewing the root level, but if I actually click on README.md it's then not rendered on that page.

**Comment by orsharir** [comment]
It does work on all pages, however, github sometimes loads pages in a way that the extension fails to detect. As a temporary fix you can simply refresh the page.

**Comment by adefazio** [comment]
I see. I got it to render after refreshing a few times.

**Comment by orsharir** [comment]
I'm reopening this so I'll remember to fix this bug without the need to refresh this page.

**Comment by Mottie** [comment]
You can add this code to re-render the page after GitHub loads in a page dynamically:

```js
document.addEventListener("pjax:end", function(){
    MathJax.Hub.Queue(["Typeset", MathJax.Hub]);
});
```

**Comment by orsharir** [comment]
Thank you for your suggestion. I'm currently working on including it.
