### ISSUE TITLE
Underscore conflict problem (fixed)

### ISSUE THREAD

**Issue by raffaello-camoriano** [orsharir/github-mathjax#36]
It recently happened to me that the plugin  would not render some equations involving underscores, probably due to a conflict with GitHub's markdown renderer.

e.g., expressions of the form `$\bar{x}_{i'}$` would not be rendered in GitHub issues, while `$x_i$` would.

I found out that backslashing the troublesome underscores fixed the problem in this case, as it was suggested for related problems in https://github.com/mathjax/MathJax/issues/329

e.g. `$\bar{x}\_{i'}$`

**Comment by traversaro** [comment]
Normally also having a space can help, i.e. (`$\bar{x} _{i'}$`):

$\bar{x}\_{i'}$
