### ISSUE TITLE
Conditional independence notation not support

### ISSUE THREAD

**Issue by dxxzst** [orsharir/github-mathjax#42]
https://www.johndcook.com/blog/2020/03/27/conditional-independence-notation/
$\perp\!\!\!\perp$

**Comment by muzimuzhi** [comment]
Duplicate of #16. Try `$\perp\\!\\!\\!\perp$` or `$\perp\kern-9mu\perp$`: 

$\perp\\!\\!\\!\perp$ or $\perp\kern-9mu\perp$

**Comment by dxxzst** [comment]
@muzimuzhi Thanks
$\perp\kern-9mu\perp$
